### ISSUE TITLE
Issue with font-family and placing main sections in correct columns

### ISSUE THREAD

**Issue by riannazandbelt** [riannazandbelt/components-on-a-grid#2]
Hi @mackenzierose,

I'm having two minor issues with my code:

1. When I run the assignment through Markbot, I get a message saying that it expected a different value in the font family. I tried playing around with the double vs single quotation marks and removing the sans-serif portion to no avail.

2. Also I tried moving the figures in the MAIN section to each their respective column and rows by targeting each figure through the figure:nth child(1) and figure:nth child(2) (also tried targeting main:nth child (1)), but either both stayed in the same place or both moved to the other column. Is there another way to target just one figure to move it over to the second column?

Thank you in advance! :)

<img width="1236" alt="Screen Shot 2020-09-18 at 3 25 14 PM" src="https://user-images.githubusercontent.com/55094049/93811279-dbcb3400-fc1d-11ea-8e78-3b43d5bc712f.png">

**Comment by MacKenzieRose** [comment]
Hi!

So a super good start!

First thing to look at is your `grid-template-area`. Because the two `figures` need to exist in two separate grid areas, the template needs to have a third area name, to replace one of the existing `main` designations.

The next thing is to then tell your CSS which things go in which `grid-area`. This means adding a little bit of code, which I've gotten started for you below, with new code for your .pano class: 

`.pano {`
`  grid-area: masthead`
`}`

Let me know how that goes, and tag me again if you need more help 😸

**Comment by MacKenzieRose** [comment]
I just realized I didn't answer your font question!

That error is because you haven't included Georgia anywhere in the CSS file; there are two fonts for this assignment :)

**Comment by riannazandbelt** [comment]
@MacKenzieRose 

Thank you for the help with the font family, that fixed it! However, I'm still not able to fix the issue with the figures. I've changed one of the grid-template-area names to banner to differentiate the two, and added grid-area to each of the figures, but they still aren't moving into their correct positions. Any more advice? :)

**Comment by MacKenzieRose** [comment]
Have you pushed your code? What I can see still has 2 mains in your `grid-template-areas`

**Comment by riannazandbelt** [comment]
Sorry, I hadn't! Just did it now!

**Comment by MacKenzieRose** [comment]
The biggest struggle you're having is that your figures aren't actually acting as part of your grid system. To fix that, let's add `display: contents;` to your `main` tag in your CSS.

The second thing is that the CSS selectors for the figures need to say `nth-of-type` not `nth-child`

Let me know if you need more help after that 🙂
